### ISSUE TITLE
Как собрать Цезий под Windows?

### ISSUE THREAD

**Issue by z-hunter** [spline1986/caesium#2]
К сожалению, ничего не знаю про Питон, пытаюсь тупо запустить и получаю ошибку:

> Traceback (most recent call last):
>   File "E:\dev\caesium-master\caesium.py", line 3, in <module>
>     import curses, os, urllib.request, urllib.parse, base64, codecs, pickle, time, subprocess, re, hashlib, webbrowser, locale
>   File "D:\Dev.dir\Python3\lib\curses\__init__.py", line 13, in <module>
>     from _curses import *
> ModuleNotFoundError: No module named '_curses'

Что делать?

**Comment by jmaks** [comment]
Данная строка явно указывает на загружаемые при инициализации "движка" модули python и прочие системные утилиты и библиотеки.

> import curses, os, urllib.request, urllib.parse, base64, codecs, pickle, time, subprocess, re, hashlib, webbrowser, locale


Нужно добавить в окружение, в системные переменные запрашиваемые модули, и всё вероятно запустится. 
Хотя тут не уверен; нужно мнение тех кто более плотно работал с python @btimofeev @vit1-irk @Difrex , а в частности, создателя *caesium* -- потому как изначально цезий разрабатывался ориентируясь на *nix-like среду.

Либо создать необходимое окружение -- например есть проект (cygwin)[https://www.cygwin.com/]; позволяет сделать unix среду в windows;
При установке, подгружает и позволяет выбрать для настройки/установки дополнительные библиотеки, программы и т.д.

**Comment by btimofeev** [comment]
Через cygwin можно запускать, вот тут есть инструкция
http://idec.spline-online.tk/CeOJ4kPpZBmv7ji3BFRL

чт, 9 янв. 2020 г., 20:42 Maksim <notifications@github.com>:

**Comment by jmaks** [comment]
Сделаю, пожалуй копипасту сообщения с ноды и сюда...

> >> Напрямую его не запустишь в винде. Можно запустить через cygwin
> z-Hunter> А есть где-то какой-то FAQ, как, не вдаваясь в детали, запустить через Cygwin?
> 
> Вот обещанная инструкция:
> 
> 1. Качаем  https://cygwin.com/setup-x86_64.exe ( https://cygwin.com/setup-x86.exe для 32-битной винды) и запускаем.
> 2. Выбираем установку из интернета (далее отвечаем на тривиальные вопросы о путях установки и настройках прокси-сервера, выбираем зеркало).
> 3. Выбор пакетов. Необходимо установить следующие пакеты: git, python3, ncurses, nano (в окне выбора пакетов есть поиск).
> 4. После запусска терминала необходимо клонировать актуальную версию caesium:
> ====
> $ git clone  https://github.com/idec-net/caesium.git
> ====
> 5. После этого достаточно зайти в директорию цезия и запустить его:
> ====
> cd caesium
> ./caesium.py
> ====
> Редактировать конфигурационный файл можно либо нажав E в цезии, либо напрямую:
> ====
> $ nano caesium/caesium.cfg
> ====
> Не очень удобно, но пользоваться можно :)

**Comment by z-hunter** [comment]
Спасибо за исчерпывающие ответы!
