### ISSUE TITLE
fetcher.py: not found [android]

### ISSUE THREAD

**Issue by btimofeev** [spline1986/caesium#5]
На андроиде в терминале Termux при попытке скачать сообщения выдает в консоль ошибку:

./fetcher.py -w -n "http://spline.rooker.ru/ii/ii-point.php?q=/" -e develop.16,game.rogue.14,ii.14,linux.14,music.14,pipe.2032,python.15,ru.humor.14 -t "btimofeev"
/data/data/com.termux/files/usr/bin/sh: 1: ./fetcher.py: not found

**Comment by spline1986** [comment]
А по факту по указанному пути фетчер имеется? Цезий пока рассчитан исключительно на работу в своей директории. В репозитории фетчер лежит в корне проекта. И да. Обновись до 0.2 (только что зафиксировал).

**Comment by btimofeev** [comment]
Обновился. Фетчер лежит рядом. Из директории цезия запускаю его командой python caesium.py. Ошибка та же. Не видит почему-то его.

**Comment by btimofeev** [comment]
Опытным путем установил, что для Termux надо так запускать:

subprocess.Popen("python ./fetcher.py", shell=True)

Для десктопа такое решение не лучший вариант, у себя на андроиде исправлю. Странный этот Termux.

**Comment by spline1986** [comment]
А права на запуск у fetcher.py имеются при этом? Косяк то странный.

**Comment by btimofeev** [comment]
Имеются:
$ cd caesium
$ ls -l fetcher.py caesium.py
-rwx------    1 u0_a347  u0_a347      39296 Apr 12 23:31 caesium.py
-rwx------    1 u0_a347  u0_a347       5893 Apr 12 17:21 fetcher.py
$ ./caesium.py
-bash: ./caesium.py: /usr/bin/env: bad interpreter: No such file or directory
$ less /usr/bin/env
/usr/bin/env: No such file or directory

Программу env я обнаружил по пути /system/bin/env
Файловая система странная.

**Comment by spline1986** [comment]
Слыхал я да, что там несколько странное прочтение стандартов.
