### ISSUE TITLE
Патч для окошка msgid и адреса

### ISSUE THREAD

**Issue by vit1-irk** [spline1986/caesium#8]
Вот. Всего на пару строк.
Скачиваешь файл, помещаешь в каталог с Цезием. Потом набираешь git apply msgid.patch и делаешь коммит.

<https://ii-net.tk/ii/files/msgid.patch>

При нажатии на клавишу M выйдет окошко с msgid и адресом станции. Уже протестировал патч везде, где можно. В окне исходящих падений нет.

**Comment by spline1986** [comment]
Спасибо. Добавил в апстрим. Правда добавил проверку на ширину терминала ещё.
